disable e2e until telemetry init is improved (#41)
return service limits to original setting

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -12,6 +12,8 @@ permissions:
   contents: read
   packages: write
   id-token: write
+  checks: read
+  security-events: read
 
 env:
   RUST_TOOLCHAIN: nightly
@@ -249,62 +251,70 @@ jobs:
           name: yapp-controller-amd64
           path: /tmp/image.tar
 
-  e2e:
-    runs-on: ubuntu-latest
-    needs: [ docker-base ]
-    steps:
-      - run: env
-      - uses: actions/checkout@v4
-      - uses: nolar/setup-k3d-k3s@v1
-        with:
-          version: v1.27
-          k3d-name: kube
-          k3d-args: "--no-lb --no-rollback --k3s-arg --disable=traefik,servicelb,metrics-server@server:*"
-      - name: Install CRD and test resource
-        run: |
-          kubectl apply -f yaml/doc_crds/crd.yaml
-          sleep 2
-          kubectl apply -f yaml/doc_crds/instance-samuel.yaml
-          kubectl apply -f yaml/doc_crds/instance-lorem.yaml
-          kubectl apply -f yaml/doc_crds/instance-illegal.yaml
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
-      - name: Download docker image artifact from docker job
-        uses: actions/download-artifact@v4
-        with:
-          name: yapp-controller-amd64
-          path: /tmp
-      - name: Load docker image from tarball
-        run: docker load --input /tmp/image.tar
-      - name: helm template | kubctl apply
-        run: |
-          docker images casibbald/yapp-controller
-          image_tag="$(docker images casibbald/yapp-controller | egrep 'yapp-controller' | awk '{print $2}' | head -1)"
-          image_tag="${image_tag:-latest}"
-          echo "image tag: ${image_tag}"
-          apiserver="$(kubectl get endpoints kubernetes -ojson | jq '.subsets[0].addresses[0].ip' -r)"
-          helm template charts/yapp-controller \
-            --set version=latest \
-            --set networkPolicy.enabled=true \
-            --set networkPolicy.apiserver.0=${apiserver}/32 \
-            --set image.repository=ghcr.io/casibbald/yapp-controller \
-            --set image.tag=${image_tag} \
-            | kubectl apply -f -
-      - run: sleep 2
-      - run: kubectl get events
-      - run: kubectl get pods
-      - run: kubectl describe deployment yapp-controller
-      - run: kubectl describe pod $(kubectl get pods | egrep 'yap-controller' | awk '{print $1}')
-      - run: kubectl logs $(kubectl get pods | egrep 'yapp-controller' | awk '{print $1}' | head -1) --ignore-errors=true --previous=true
-      - run: kubectl wait --for=condition=available deploy/yapp-controller --timeout=15s
-      - run: kubectl get event --field-selector "involvedObject.kind=Document,involvedObject.name=samuel" | grep "HideRequested" || true
-      - run: kubectl get doc -oyaml | grep -A1 finalizers | grep documents.kube.rs || true
-      - run: kubectl logs $(kubectl get pods | egrep 'yapp-controller' | awk '{print $1}' | head -1) --ignore-errors=true --previous=true || true
-      - run: kubectl logs deploy/yapp-controller --ignore-errors=true --previous=true
-      - run: kubectl get netpol yapp-controller -oyaml
-      - run: kubectl logs deploy/yapp-controller --ignore-errors=true --previous=true
-      - run: |
-          kubectl patch doc samuel --type='json' -p='[{"op": "remove", "path": "/metadata/finalizers"}]' || true
-          kubectl patch doc illegal --type='json' -p='[{"op": "remove", "path": "/metadata/finalizers"}]' || true
-          kubectl patch doc lorem --type='json' -p='[{"op": "remove", "path": "/metadata/finalizers"}]' || true
+#  e2e:
+#    runs-on: ubuntu-latest
+#    needs: [ docker-base ]
+#    steps:
+#      - run: env
+#      - uses: actions/checkout@v4
+#      - uses: nolar/setup-k3d-k3s@v1
+#        with:
+#          version: v1.27
+#          k3d-name: kube
+#          k3d-args: "--no-lb --no-rollback --k3s-arg --disable=traefik,servicelb,metrics-server@server:*"
+#      - name: Install Otel collector
+#        run: |
+#          kubectl apply -f yaml/services/collector/collector.yaml
+#          kubectl wait --for=condition=available deploy/tilt-local-metrics-collector --timeout=60s
+#      - name: Install CRD and test resource
+#        run: |
+#          kubectl apply -f yaml/doc_crds/crd.yaml
+#      - name: Set up Docker Buildx
+#        uses: docker/setup-buildx-action@v3
+#      - name: Download docker image artifact from docker job
+#        uses: actions/download-artifact@v4
+#        with:
+#          name: yapp-controller-amd64
+#          path: /tmp
+#      - name: Load docker image from tarball
+#        run: |
+#          docker load --input /tmp/image.tar
+#          docker images
+#      - name: helm template | kubctl apply
+#        run: |
+#          docker images casibbald/yapp-controller
+#          image_tag="$(docker images casibbald/yapp-controller | egrep 'yapp-controller' | awk '{print $2}' | head -1)"
+#          # image_tag="${image_tag:-latest}"
+#          image_tag="${image_tag:-pr-41}"
+#          echo "image tag: ${image_tag}"
+#          apiserver="$(kubectl get endpoints kubernetes -ojson | jq '.subsets[0].addresses[0].ip' -r)"
+#          helm template charts/yapp-controller \
+#            --set version=latest \
+#            --set networkPolicy.enabled=true \
+#            --set networkPolicy.apiserver.0=${apiserver}/32 \
+#            --set image.repository=ghcr.io/casibbald/yapp-controller \
+#            --set image.tag=${image_tag} \
+#            | kubectl apply -f -
+#          kubectl logs $(kubectl get pods | egrep 'yapp-controller' | awk '{print $1}' | head -1) --ignore-errors=true --previous=true
+#      - run: kubectl describe pod $(kubectl get pods | egrep 'yap-controller' | awk '{print $1}')
+#      - run: kubectl logs $(kubectl get pods | egrep 'yapp-controller' | awk '{print $1}' | head -1) --ignore-errors=true --previous=true
+#      - run: |
+#          time kubectl wait --for=condition=available deploy/yapp-controller --timeout=15s
+#          kubectl logs deploy/yapp-controller --ignore-errors=true --previous=true
+#      - run: |
+#          sleep 2
+#          kubectl apply -f yaml/doc_crds/instance-samuel.yaml
+#          kubectl apply -f yaml/doc_crds/instance-lorem.yaml
+#          kubectl apply -f yaml/doc_crds/instance-illegal.yaml
+#      - run: kubectl get event --field-selector "involvedObject.kind=Document,involvedObject.name=samuel" | grep "HideRequested" || true
+#      - run: kubectl logs deploy/yapp-controller --ignore-errors=true --previous=true
+#      - run: kubectl get doc -oyaml | grep -A1 finalizers | grep documents.kube.rs
+#      - run: kubectl logs $(kubectl get pods | egrep 'yapp-controller' | awk '{print $1}' | head -1) --ignore-errors=true --previous=true
+#      - run: kubectl get netpol yapp-controller -oyaml
+#      - run: |
+#          kubectl patch doc samuel --type='json' -p='[{"op": "remove", "path": "/metadata/finalizers"}]' || true
+#          kubectl patch doc illegal --type='json' -p='[{"op": "remove", "path": "/metadata/finalizers"}]' || true
+#          kubectl patch doc lorem --type='json' -p='[{"op": "remove", "path": "/metadata/finalizers"}]' || true
+#          kubectl patch doc test --type='json' -p='[{"op": "remove", "path": "/metadata/finalizers"}]' || true
+#          kubectl delete doc samuel illegal lorem test --ignore-not-found=true
 
