reactivate e2e tests (#53)
* reactivate e2e tests

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -251,70 +251,67 @@ jobs:
           name: yair-controller-amd64
           path: /tmp/image.tar
 
-#  e2e:
-#    runs-on: ubuntu-latest
-#    needs: [ docker-base ]
-#    steps:
-#      - run: env
-#      - uses: actions/checkout@v4
-#      - uses: nolar/setup-k3d-k3s@v1
-#        with:
-#          version: v1.27
-#          k3d-name: kube
-#          k3d-args: "--no-lb --no-rollback --k3s-arg --disable=traefik,servicelb,metrics-server@server:*"
-#      - name: Install Otel collector
-#        run: |
-#          kubectl apply -f yaml/services/collector/collector.yaml
-#          kubectl wait --for=condition=available deploy/tilt-local-metrics-collector --timeout=60s
-#      - name: Install CRD and test resource
-#        run: |
-#          kubectl apply -f yaml/doc_crds/crd.yaml
-#      - name: Set up Docker Buildx
-#        uses: docker/setup-buildx-action@v3
-#      - name: Download docker image artifact from docker job
-#        uses: actions/download-artifact@v4
-#        with:
-#          name: yair-controller-amd64
-#          path: /tmp
-#      - name: Load docker image from tarball
-#        run: |
-#          docker load --input /tmp/image.tar
-#          docker images
-#      - name: helm template | kubctl apply
-#        run: |
-#          docker images casibbald/yair-controller
-#          image_tag="$(docker images casibbald/yair-controller | egrep 'yair-controller' | awk '{print $2}' | head -1)"
-#          # image_tag="${image_tag:-latest}"
-#          image_tag="${image_tag:-pr-41}"
-#          echo "image tag: ${image_tag}"
-#          apiserver="$(kubectl get endpoints kubernetes -ojson | jq '.subsets[0].addresses[0].ip' -r)"
-#          helm template charts/yair-controller \
-#            --set version=latest \
-#            --set networkPolicy.enabled=true \
-#            --set networkPolicy.apiserver.0=${apiserver}/32 \
-#            --set image.repository=ghcr.io/casibbald/yair-controller \
-#            --set image.tag=${image_tag} \
-#            | kubectl apply -f -
-#          kubectl logs $(kubectl get pods | egrep 'yair-controller' | awk '{print $1}' | head -1) --ignore-errors=true --previous=true
-#      - run: kubectl describe pod $(kubectl get pods | egrep 'yap-controller' | awk '{print $1}')
-#      - run: kubectl logs $(kubectl get pods | egrep 'yair-controller' | awk '{print $1}' | head -1) --ignore-errors=true --previous=true
-#      - run: |
-#          time kubectl wait --for=condition=available deploy/yair-controller --timeout=15s
-#          kubectl logs deploy/yair-controller --ignore-errors=true --previous=true
-#      - run: |
-#          sleep 2
-#          kubectl apply -f yaml/doc_crds/instance-samuel.yaml
-#          kubectl apply -f yaml/doc_crds/instance-lorem.yaml
-#          kubectl apply -f yaml/doc_crds/instance-illegal.yaml
-#      - run: kubectl get event --field-selector "involvedObject.kind=Document,involvedObject.name=samuel" | grep "HideRequested" || true
-#      - run: kubectl logs deploy/yair-controller --ignore-errors=true --previous=true
-#      - run: kubectl get doc -oyaml | grep -A1 finalizers | grep documents.kube.rs
-#      - run: kubectl logs $(kubectl get pods | egrep 'yair-controller' | awk '{print $1}' | head -1) --ignore-errors=true --previous=true
-#      - run: kubectl get netpol yair-controller -oyaml
-#      - run: |
-#          kubectl patch doc samuel --type='json' -p='[{"op": "remove", "path": "/metadata/finalizers"}]' || true
-#          kubectl patch doc illegal --type='json' -p='[{"op": "remove", "path": "/metadata/finalizers"}]' || true
-#          kubectl patch doc lorem --type='json' -p='[{"op": "remove", "path": "/metadata/finalizers"}]' || true
-#          kubectl patch doc test --type='json' -p='[{"op": "remove", "path": "/metadata/finalizers"}]' || true
-#          kubectl delete doc samuel illegal lorem test --ignore-not-found=true
+  e2e:
+    runs-on: ubuntu-latest
+    needs: [ docker-base ]
+    steps:
+      - run: env
+      - uses: actions/checkout@v4
+      - uses: nolar/setup-k3d-k3s@v1
+        with:
+          version: v1.27
+          k3d-name: kube
+          k3d-args: "--no-lb --no-rollback --k3s-arg --disable=traefik,servicelb,metrics-server@server:*"
+      - name: Install Otel collector
+        run: |
+          kubectl apply -f yaml/services/collector/collector.yaml
+          kubectl wait --for=condition=available deploy/tilt-local-metrics-collector --timeout=60s
+      - name: Install CRD and test resource
+        run: |
+          kubectl apply -f yaml/doc_crds/crd.yaml
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
+      - name: Download docker image artifact from docker job
+        uses: actions/download-artifact@v4
+        with:
+          name: yair-controller-amd64
+          path: /tmp
+      - name: Load docker image from tarball
+        run: |
+          docker load --input /tmp/image.tar
+          docker images
+      - name: helm template | kubctl apply
+        run: |
+          docker images casibbald/yair-controller
+          image_tag="$(docker images casibbald/yair-controller | egrep 'yair-controller' | awk '{print $2}' | head -1)"
+          image_tag="${image_tag:-latest}"
+          echo "image tag: ${image_tag}"
+          apiserver="$(kubectl get endpoints kubernetes -ojson | jq '.subsets[0].addresses[0].ip' -r)"
+          helm template charts/yair-controller \
+            --set version=latest \
+            --set networkPolicy.enabled=true \
+            --set networkPolicy.apiserver.0=${apiserver}/32 \
+            --set image.repository=ghcr.io/casibbald/yair-controller \
+            --set image.tag=${image_tag} \
+            | kubectl apply -f -
+          kubectl logs $(kubectl get pods | egrep 'yair-controller' | awk '{print $1}' | head -1) --ignore-errors=true --previous=true
+      - run: kubectl describe pod $(kubectl get pods | egrep 'yair-controller' | awk '{print $1}')
+      - run: kubectl logs $(kubectl get pods | egrep 'yair-controller' | awk '{print $1}' | head -1) --ignore-errors=true --previous=true
+      - run: |
+          time kubectl wait --for=condition=available deploy/yair-controller --timeout=15s
+          kubectl logs deploy/yair-controller --ignore-errors=true --previous=true
+      - run: |
+          sleep 2
+          kubectl apply -f yaml/doc_crds/instance-samuel.yaml
+          kubectl apply -f yaml/doc_crds/instance-lorem.yaml
+          kubectl apply -f yaml/doc_crds/instance-illegal.yaml
+      - run: kubectl get event --field-selector "involvedObject.kind=Document,involvedObject.name=samuel" | grep "HideRequested"
+      - run: kubectl get doc -oyaml | grep -A1 finalizers | grep documents.kube.rs
+      - run: kubectl get netpol yair-controller -oyaml
+      - run: |
+          kubectl patch doc samuel --type='json' -p='[{"op": "remove", "path": "/metadata/finalizers"}]' || true
+          kubectl patch doc illegal --type='json' -p='[{"op": "remove", "path": "/metadata/finalizers"}]' || true
+          kubectl patch doc lorem --type='json' -p='[{"op": "remove", "path": "/metadata/finalizers"}]' || true
+          kubectl patch doc test --type='json' -p='[{"op": "remove", "path": "/metadata/finalizers"}]' || true
+          kubectl delete doc samuel illegal lorem test --ignore-not-found=true
 
